import { INDIGO, TEXT_SEC, BORDER, CLAY, BG, SURFACE, CREAM, SAND, FONT_SERIF, FONT_SANS } from '../../../tokens'
import type { WebPage } from '../../types'
import './Heritage.scss'

interface Props { onNavigate: (p: WebPage) => void }

export default function Heritage({ onNavigate }: Props) {
  return (
    <div className="heritage-page" style={{ background: BG }}>
      <section style={{ position: 'relative', overflow: 'hidden', height: '72vh', minHeight: 540 }}><img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1600&h=1000&fit=crop&auto=format" alt="Atlas mountains" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} /><div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to right, rgba(30,47,68,0.75) 0%, rgba(30,47,68,0.2) 70%)' }} /><div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center' }}><div style={{ maxWidth: 1280, width: '100%', margin: '0 auto', padding: '0 40px' }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: SAND, marginBottom: 16 }}>Our Heritage</div><h1 style={{ fontFamily: FONT_SERIF, fontSize: 64, fontWeight: 500, color: CREAM, margin: 0, lineHeight: 1.05, maxWidth: 560 }}>Amazigh craft. Contemporary form.</h1></div></div></section>
      <section style={{ maxWidth: 800, margin: '0 auto', padding: '88px 40px' }}><p style={{ fontFamily: FONT_SERIF, fontSize: 22, color: INDIGO, lineHeight: 1.7, margin: 0, marginBottom: 24 }}>IZLI was founded on a single belief: that Amazigh craft traditions are not historical artifacts — they are living languages, capable of speaking in contemporary forms.</p><p style={{ fontSize: 15, color: TEXT_SEC, lineHeight: 1.8, margin: 0 }}>The Amazigh people have been weaving, dyeing, and marking cloth for thousands of years across North Africa and the Sahara. Their geometric patterns — encoded in stone, in jewelry, in woven rugs — carry genealogy, belonging, and memory. IZLI translates these languages into garments designed for the present.</p></section>
      <section style={{ background: SURFACE, borderTop: `1px solid ${BORDER}`, borderBottom: `1px solid ${BORDER}` }}><div style={{ maxWidth: 1280, margin: '0 auto', padding: '0 40px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 0 }}><div style={{ padding: '72px 64px 72px 0' }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: CLAY, marginBottom: 16 }}>Tifinagh Script</div><h2 style={{ fontFamily: FONT_SERIF, fontSize: 40, fontWeight: 500, color: INDIGO, margin: 0, lineHeight: 1.15, marginBottom: 20 }}>The oldest living script in the world.</h2><p style={{ fontSize: 14, color: TEXT_SEC, lineHeight: 1.8, margin: 0, marginBottom: 20 }}>Tifinagh is the ancient alphabet of the Amazigh people — one of the oldest scripts still in active use. Its marks appear on rock surfaces across the Sahara and on textiles woven by Berber communities from Morocco to Mali.</p><p style={{ fontSize: 14, color: TEXT_SEC, lineHeight: 1.8, margin: 0, marginBottom: 28 }}>Each IZLI garment that carries Tifinagh embroidery is produced in collaboration with artisans who learned the script from their mothers. The marks are not decoration — they are meaning.</p><button onClick={() => onNavigate('stories')} style={{ padding: '11px 22px', background: INDIGO, color: CREAM, border: 'none', borderRadius: 10, fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: FONT_SANS }}>Read: Indigo as Memory →</button></div><div style={{ overflow: 'hidden' }}><img src="https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=700&h=600&fit=crop&auto=format" alt="Tifinagh" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} /></div></div></section>
      <section style={{ maxWidth: 1280, margin: '0 auto', padding: '88px 40px' }}><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 64, alignItems: 'center' }}><div style={{ borderRadius: 16, overflow: 'hidden', aspectRatio: '1' }}><img src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=700&h=700&fit=crop&auto=format" alt="Indigo" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} /></div><div><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: TEXT_SEC, marginBottom: 16 }}>Indigo Dyeing</div><h2 style={{ fontFamily: FONT_SERIF, fontSize: 40, fontWeight: 500, color: INDIGO, margin: 0, lineHeight: 1.15, marginBottom: 20 }}>Blue that has traveled for centuries.</h2><p style={{ fontSize: 14, color: TEXT_SEC, lineHeight: 1.8, margin: 0, marginBottom: 20 }}>Indigo dyeing arrived in North Africa through trans-Saharan trade routes, where it became embedded in Tuareg and Berber textile traditions. The iconic indigo-dyed turbans of the Tuareg gave them the name "Blue Men of the Sahara."</p><p style={{ fontSize: 14, color: TEXT_SEC, lineHeight: 1.8, margin: 0 }}>IZLI works with dyers in the Draa Valley in southern Morocco, preserving natural indigo dyeing techniques that have been practiced for over 500 years. Our Indigo Memory collection documents this process from plant to garment.</p></div></div></section>
      <section style={{ background: INDIGO, padding: '72px 40px' }}><div style={{ maxWidth: 1280, margin: '0 auto' }}><h2 style={{ fontFamily: FONT_SERIF, fontSize: 36, fontWeight: 500, color: CREAM, margin: 0, marginBottom: 48, textAlign: 'center' }}>How we work</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 40 }}>{[{ icon: '◯', title: 'Community-led', desc: 'Our garments are co-developed with the communities whose heritage they draw from.' }, { icon: '◇', title: 'Research-first', desc: 'Every collection begins with archival research, fieldwork, and collaboration with historians.' }, { icon: '◈', title: 'Artisan-made', desc: 'Our embroidery, weaving, and dyeing is done by artisans working in traditional techniques.' }, { icon: '⬠', title: 'Slow production', desc: 'We make limited quantities, made thoughtfully. No waste, no excess.' }].map(v => (<div key={v.title}><div style={{ fontSize: 24, color: SAND, marginBottom: 14 }}>{v.icon}</div><div style={{ fontFamily: FONT_SERIF, fontSize: 18, fontWeight: 500, color: CREAM, marginBottom: 10 }}>{v.title}</div><div style={{ fontSize: 13, color: 'rgba(231,223,210,0.6)', lineHeight: 1.7 }}>{v.desc}</div></div>))}</div></div></section>
      <section style={{ padding: '80px 40px', textAlign: 'center', maxWidth: 640, margin: '0 auto' }}><h2 style={{ fontFamily: FONT_SERIF, fontSize: 36, fontWeight: 500, color: INDIGO, margin: 0, marginBottom: 16 }}>Heritage is a living practice.</h2><p style={{ fontSize: 15, color: TEXT_SEC, lineHeight: 1.75, margin: 0, marginBottom: 32 }}>The Community Lab is where we invite makers, archivists, and memory-keepers to contribute to the ongoing research. Every contribution shapes what IZLI makes next.</p><button onClick={() => onNavigate('community-lab')} style={{ padding: '13px 28px', background: INDIGO, color: CREAM, border: 'none', borderRadius: 10, fontSize: 14, fontWeight: 600, cursor: 'pointer', fontFamily: FONT_SANS }}>Explore the Lab →</button></section>
    </div>
  )
}