import { Router } from 'express';
import { authRouter } from '../modules/auth/routes.js';
import { usersRouter } from '../modules/users/routes.js';
import { resourcesRouter } from './resources.routes.js';
import { uploadRouter } from './upload.routes.js';
import { healthRouter } from './health.routes.js';
import { qrRouter } from '../modules/qr/routes.js';
import { analyticsRoutes } from '../modules/analytics/routes.js';
import { adminCollectionsRoutes, collectionsRoutes } from '../modules/collections/routes.js';
import { adminCollectionsPageRoutes, collectionsPageRoutes } from '../modules/websiteBuilder/routes.js';
import { adminHomePageRoutes, homePageRoutes } from '../modules/websiteBuilder/homePageRoutes.js';
import ordersRoutes from '../modules/orders/routes.js';
import shippingRoutes from '../modules/shipping/routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/resources', resourcesRouter);
apiRouter.use('/uploads', uploadRouter);
apiRouter.use('/qr', qrRouter);
apiRouter.use('/analytics', analyticsRoutes);
apiRouter.use('/collections', collectionsRoutes);
apiRouter.use('/admin/collections', adminCollectionsRoutes);
apiRouter.use('/website-builder/collections-page', collectionsPageRoutes);
apiRouter.use('/admin/website-builder/collections-page', adminCollectionsPageRoutes);
apiRouter.use('/website-builder/home-page', homePageRoutes);
apiRouter.use('/admin/website-builder/home-page', adminHomePageRoutes);
apiRouter.use('/orders', ordersRoutes);
apiRouter.use('/shipping', shippingRoutes);
