export const TUNISIAN_GOVERNORATES: Record<string, string[]> = {
  Ariana: ['Ariana', 'Ettadhamen', 'Kalaat El Andalous', 'La Soukra', 'Mnihla', 'Raoued', 'Sidi Thabet'],
  Beja: ['Amdoun', 'Beja', 'Goubellat', 'Medjez el-Bab', 'Nefza', 'Teboursouk', 'Testour', 'Thibar'],
  'Ben Arous': ['Ben Arous', 'Bou Mhel el-Bassatine', 'Ezzahra', 'Fouchana', 'Hammam Lif', 'Hammam Chott', 'Mégrine', 'Mornag', 'Radès'],
  Bizerte: ['Bizerte', 'El Alia', 'Ghar el-Melh', 'Ghezala', 'Joumine', 'Mateur', 'Menzel Bourguiba', 'Menzel Jemil', 'Ras Jebel', 'Sejnane', 'Tinja', 'Utique'],
  Gabes: ['El Hamma', 'Gabès', 'Ghannouch', 'Mareth', 'Matmata', 'Métouia', 'Nouvelle Matmata'],
  Gafsa: ['Belkhir', 'El Guettar', 'Gafsa', 'Mdhilla', 'Métlaoui', 'Redeyef', 'Sened', 'Sidi Aïch'],
  Jendouba: ['Aïn Draham', 'Balta-Bou Aouane', 'Bou Salem', 'Fernana', 'Ghardimaou', 'Jendouba', 'Tabarka'],
  Kairouan: ['Aïn Djeloula', 'Bou Hajla', 'Chebika', 'Haffouz', 'Hajeb El Ayoun', 'Kairouan', 'Nasrallah', 'Oueslatia', 'Sbikha'],
  Kasserine: ['Fériana', 'Foussana', 'Haïdra', 'Jedelienne', 'Kasserine', 'Mejel Bel Abbès', 'Sbeïtla', 'Sbiba', 'Thala'],
  Kebili: ['Douz', 'Faouar', 'Kebili', 'Souk Lahad'],
  Kef: ['Dahmani', 'El Ksour', 'Jérissa', 'Kalaat Senan', 'Le Kef', 'Nebeur', 'Sakiet Sidi Youssef', 'Tajerouine'],
  Mahdia: ['Bou Merdes', 'Chebba', 'Chorbane', 'El Jem', 'Essouassi', 'Hebira', 'Ksour Essef', 'Mahdia', 'Melloulèche', 'Ouled Chamekh', 'Sidi Alouane'],
  Manouba: ['Borj El Amri', 'Douar Hicher', 'El Battan', 'Jedaida', 'Manouba', 'Mornaguia', 'Oued Ellil', 'Tebourba'],
  Medenine: ['Ben Gardane', 'Beni Khedache', 'Djerba Ajim', 'Djerba Houmet Souk', 'Djerba Midoun', 'Medenine', 'Sidi Makhlouf', 'Zarzis'],
  Monastir: ['Bekalta', 'Bembla', 'Beni Hassen', 'Jemmal', 'Ksar Hellal', 'Ksibet el-Médiouni', 'Moknine', 'Monastir', 'Ouerdanine', 'Sahline', 'Sayada-Lamta-Bou Hajar', 'Téboulba', 'Zéramdine'],
  Nabeul: ['Béni Khalled', 'Béni Khiar', 'Bou Argoub', 'Dar Chaabane', 'El Haouaria', 'Grombalia', 'Hammam Ghezèze', 'Hammamet', 'Kelibia', 'Korba', 'Menzel Bouzelfa', 'Menzel Temime', 'Nabeul', 'Soliman', 'Takelsa'],
  Sfax: ['Agareb', 'Bir Ali Ben Khalifa', 'El Amra', 'El Hencha', 'Graïba', 'Jebiniana', 'Kerkennah', 'Mahrès', 'Menzel Chaker', 'Sakiet Eddaïer', 'Sakiet Ezzit', 'Sfax', 'Skhira', 'Thyna'],
  'Sidi Bouzid': ['Bir El Hafey', 'Cebbala Ouled Asker', 'Jilma', 'Meknassy', 'Menzel Bouzaiane', 'Regueb', 'Sidi Bouzid', 'Souk Jedid'],
  Siliana: ['Bargou', 'Bou Arada', 'El Aroussa', 'Gaâfour', 'Kesra', 'Makthar', 'Rouhia', 'Siliana'],
  Sousse: ['Akouda', 'Bou Ficha', 'Enfidha', 'Hammam Sousse', 'Hergla', 'Kalaa Kebira', 'Kalaa Seghira', 'Kondar', 'M\'saken', 'Sidi Bou Ali', 'Sidi El Hani', 'Sousse', 'Zaouiet Ksibet Thrayet'],
  Tataouine: ['Bir Lahmar', 'Dehiba', 'Ghomrassen', 'Remada', 'Smâr', 'Tataouine'],
  Tozeur: ['Degache', 'Hazoua', 'Nefta', 'Tameghza', 'Tozeur'],
  Tunis: ['Carthage', 'La Goulette', 'La Marsa', 'Le Bardo', 'Le Kram', 'Sidi Bou Saïd', 'Tunis'],
  Zaghouan: ['Bir Mcherga', 'El Fahs', 'Nadhour', 'Saouaf', 'Zaghouan', 'Zriba'],
}
