export type WebPage =
  | 'home'
  | 'collections'
  | 'shop'
  | 'product-detail'
  | 'heritage'
  | 'stories'
  | 'community'
  | 'community-lab'
  | 'events'
  | 'about'
  | 'cart'
  | 'login'
  | 'profile'
  | 'legacy'
  | 'archives'
  | 'keeper-circle'